services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://cad_user:cad123@db:5432/cadcorp_db
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - .:/app
      - ./.env:/app/.env

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=cad_user
      - POSTGRES_PASSWORD=cad123
      - POSTGRES_DB=cadcorp_db
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: